### ISSUE TITLE
Ghost Overlay not working

### ISSUE THREAD

**Issue by theredkoolaid** [joshhunt/GhostOverlay#50] opened 2023-03-24 21:19 UTC
Ghost Overlay has been working properly for some time now. It is still being supported? Love the program and would like to continue using it.

Thanks for your time and efforts!

**Comment by joshhunt** [comment] 2023-03-27 20:40
Dupe of https://github.com/joshhunt/GhostOverlay/issues/47

**Closed as completed by joshhunt** 2023-03-27 20:40 UTC
