### ISSUE TITLE
Unable to use at all

### ISSUE THREAD

**Issue by docgoodygoods** [joshhunt/GhostOverlay#49] opened 2023-03-07 18:45 UTC
Hello,
After multiple fresh install attempts, I am unable to use the plugin at all. Upon opening game bar, the widget displays "No tracked bounties yet!" After pressing "Open Settings," Gamebar immediately crashes. When reopened, the settings pane says "Something isn't playing nice." Any time I press restart, the plugin briefly loads the settings pane and then returns to "Something went wrong with this widget."

I've made sure that I have the latest build and version of Windows 10, as well as Gamebar. 

I'm not sure what else to try, or if there is something else I'm missing to get it working. 

Thanks!

**Comment by cglatot** [comment] 2023-03-09 13:14
Same issue for me. I assume it just hasn't been updated for compatibility with Lightfall.

**Comment by Awy64** [comment] 2023-03-14 23:58
Same issue for me as well.

**Comment by CWSurpris3** [comment] 2023-03-23 19:10
@Awy64 @cglatot @docgoodygoods It's the same issue I'm having in my issue thread. You can get to Triumphs and Insights if you're quick enough, but pursuits specifically has been found to crash it, and Xbox Game Bar.

**Comment by joshhunt** [comment] 2023-03-27 20:41
Dupe of https://github.com/joshhunt/GhostOverlay/issues/47

**Closed as completed by joshhunt** 2023-03-27 20:41 UTC
